name = "flowmatik-backend"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[env.production.vars]
AI_302_API_KEY = ""

